const clubs = [
  {
    name: "Bastard Munchen",
    famerequirement: 10000,
    description: "Good players, but you're literally fighting your own team",
  },
  {
    name: "F.C. Bachira",
    famerequirement: 5555,
    description: "Wym there's other players",
  },
  {
    name: "Manshine City",
    famerequirement: 7500,
    description: "Nagi gotta come back... right??",
  },
  {
    name: "Ubers",
    famerequirement: 8000,
    description: "Marc Snuffy the goat teacher",
  },
  {
    name: "Paris X Gen",
    famerequirement: 9999,
    description: "Aka Destroyer Mode Rin carrying the whole team",
  },
  {
    name: "Re Al",
    famerequirement: 15000,
    description: "Best club in the world.",
  },
];

const players = [
  {
    name: "Rin Itoshi",
    cumulative_stats: 95,
    stats: {
      speed: 90,
      defense: 95,
      passing: 86,
      dribble: 92,
      shoot: 95,
      offense: 95,
    },
    skills: [
      "Perfect Kick Accuracy",
      "Spatial Awareness",
      "Off the Ball",
      "Puppet Soccer",
      "Egotistic Destroyer",
    ],
  },
  {
    name: "Sae Itoshi",
    cumulative_stats: 98,
    stats: {
      speed: 87,
      defense: 73,
      passing: 98,
      dribble: 90,
      shoot: 79,
      offense: 85,
    },
    skills: [
      "Perfect Kick Technique",
      "Counter-Dribbling",
      "Reflex",
      "Meta-Vision",
    ],
  },
  {
    name: "Aiku Oliver",
    cumulative_stats: 85,
    stats: {
      speed: 81,
      defense: 93,
      passing: 83,
      dribble: 76,
      shoot: 77,
      offense: 72,
    },
    skills: [
      "Dominant Physicality",
      "Spatial Awareness",
      "Reflex",
      "Meta-Vision",
    ],
  },
  {
    name: "Baro Shoei",
    cumulative_stats: 92,
    stats: {
      speed: 80,
      defense: 68,
      passing: 61,
      dribble: 88,
      shoot: 96,
      offense: 95,
    },
    skills: ["Charging Skill", "Chop Dribbling", "Middle Shot", "Predator Eye"],
  },
  {
    name: "Niko Ikki",
    cumulative_stats: 82,
    stats: {
      speed: 78,
      defense: 84,
      passing: 88,
      dribble: 76,
      shoot: 67,
      offense: 82,
    },
    skills: ["Spatial Awareness", "Watchtower Soccer", "Meta-Vision"],
  },
  {
    name: "Chigiri Hyoma",
    cumulative_stats: 90,
    stats: {
      speed: 98,
      defense: 68,
      passing: 80,
      dribble: 93,
      shoot: 88,
      offense: 95,
    },
    skills: ["Immeasurable Speed", "44 Red Panther Sniper"],
  },
  {
    name: "Yoichi Isagi",
    cumulative_stats: 88,
    stats: {
      speed: 77,
      defense: 75,
      passing: 78,
      dribble: 70,
      shoot: 82,
      offense: 94,
    },
    skills: [
      "Direct Shot",
      "Spatial Awareness",
      "Meta-Vision",
      "Egocentrism",
      "Direct Shot",
      "Off the Ball",
      "Reflex",
      "Two Gun Volley",
    ],
  },
  {
    name: "Meguru Bachira",
    cumulative_stats: 86,
    stats: {
      speed: 84,
      defense: 68,
      passing: 88,
      dribble: 95,
      shoot: 82,
      offense: 86,
    },
    skills: ["Elastic Dribbling", "Key Passing", "Monstrance"],
  },
  {
    name: "Alexis Ness",
    cumulative_stats: 93,
    stats: {
      speed: 76,
      defense: 71,
      passing: 97,
      dribble: 90,
      shoot: 78,
      offense: 94,
    },
    skills: ["Elastic Dribbling", "Key Passing"],
  },
  {
    name: "Michael Kaiser",
    cumulative_stats: 98,
    stats: {
      speed: 91,
      defense: 74,
      passing: 81,
      dribble: 86,
      shoot: 98,
      offense: 96,
    },
    skills: ["Off the Ball", "Meta-Vision", "Predator Eye", "Kaiser Impact"],
  },
  {
    name: "Jingo Raichi",
    cumulative_stats: 81,
    stats: {
      speed: 77,
      defense: 90,
      passing: 81,
      dribble: 79,
      shoot: 82,
      offense: 82,
    },
    skills: ["Immense Stamina", "Manmarking"],
  },
  {
    name: "Rensuke Kunigami",
    cumulative_stats: 91,
    stats: {
      speed: 85,
      defense: 75,
      passing: 65,
      dribble: 71,
      shoot: 95,
      offense: 94,
    },
    skills: [
      "Dominant Physicality",
      "Ambidexterity",
      "Manmarking",
      "Jumping Power",
    ],
  },
  {
    name: "Gin Gagamaru",
    cumulative_stats: 85,
    stats: {
      speed: 87,
      defense: 93,
      passing: 88,
      dribble: 79,
      shoot: 80,
      offense: 84,
    },
    skills: ["Reflex", "Flexibility"],
  },
  {
    name: "Jin Kiyora",
    cumulative_stats: 80,
    stats: {
      speed: 82,
      defense: 76,
      passing: 80,
      dribble: 83,
      shoot: 88,
      offense: 81,
    },
    skills: [
      "Dominant Physicality",
      "Nimble Dribbling",
      "Perfect Kick Accuracy",
    ],
  },
  {
    name: "Charles Chevalier",
    cumulative_stats: 93,
    stats: {
      speed: 84,
      defense: 77,
      passing: 97,
      dribble: 89,
      shoot: 88,
      offense: 92,
    },
    skills: ["Perfect Kick Accuracy", "Meta-Vision"],
  },
  {
    name: "Nagi Seishiro",
    cumulative_stats: 92,
    stats: {
      speed: 82,
      defense: 75,
      passing: 85,
      dribble: 86,
      shoot: 92,
      offense: 91,
    },
    skills: ["Perfect Ball Control", "Trapping"],
  },
  {
    name: "Mikage Reo",
    cumulative_stats: 85,
    stats: {
      speed: 81,
      defense: 86,
      passing: 89,
      dribble: 83,
      shoot: 82,
      offense: 86,
    },
    skills: ["Dexterity", "Chameleon Style", "Meta-Vision"],
  },
  {
    name: "Genyu Yukimiya",
    cumulative_stats: 82,
    stats: {
      speed: 89,
      defense: 76,
      passing: 77,
      dribble: 91,
      shoot: 86,
      offense: 88,
    },
    skills: ["1-on-1 Emperor Style", "Immense Speed", "Gyro Shot"],
  },
  {
    name: "Ryusei Shido",
    cumulative_stats: 92,
    stats: {
      speed: 85,
      defense: 77,
      passing: 85,
      dribble: 84,
      shoot: 92,
      offense: 90,
    },
    skills: [
      "Dominant Physicality",
      "Spatial Awareness",
      "Reflex",
      "Drive Shot",
    ],
  },
  {
    name: "Jyubei Aryu",
    cumulative_stats: 80,
    stats: {
      speed: 74,
      defense: 90,
      passing: 68,
      dribble: 69,
      shoot: 79,
      offense: 76,
    },
    skills: ["Jumping Power", "Long Reach"],
  },
  {
    name: "Don Lorenzo",
    cumulative_stats: 96,
    stats: {
      speed: 83,
      defense: 99,
      passing: 87,
      dribble: 93,
      shoot: 82,
      offense: 84,
    },
    skills: ["Zombie Dribbling"],
  },
  {
    name: "Kurona Ranze",
    cumulative_stats: 83,
    stats: {
      speed: 95,
      defense: 68,
      passing: 83,
      dribble: 84,
      shoot: 72,
      offense: 86,
    },
    skills: ["Immense Speed", "Positioning"],
  },
];

const skills = {
  "1 point": ["Reflex", "Direct Shot", "Manmarking"],
  "3 points": [
    "Spatial Awareness",
    "Off the Ball",
    "Dominant Physicality",
    "Middle Shot",
    "44 Red Panther Sniper",
    "Key Passing",
    "Immense Stamina",
    "Jumping Power",
  ],
  "5 points": [
    "Perfect Kick Accuracy",
    "Puppet Soccer",
    "Perfect Kick Technique",
    "Meta-Vision",
    "Charging Skill",
    "Predator Eye",
    "Watchtower Soccer",
    "Flexibility",
    "Counter-Dribbling",
    "Nimble Dribbling",
    "Chop Dribbling",
    "Elastic Dribbling",
    "Gyro Shot",
    "Drive Shot",
    "Long Reach",
    "Immense Speed",
    "Positioning",
  ],
  "10 points": [
    "Egotistic Destroyer",
    "Immeasurable Speed",
    "Egocentrism",
    "Two Gun Volley",
    "Monstrance",
    "Kaiser Impact",
    "Ambidexterity",
    "Perfect Ball Control",
    "Trapping",
    "Dexterity",
    "Chameleon Style",
    "Zombie Dribbling",
  ],
};

export { clubs };
export { players };
export { skills }