[
  {
    name: "Rin Itoshi",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [
      "Advanced Shooting",
      "Destroyer Mode",
      "Off the Ball",
      "Advanced Dribbling",
    ],
    position: null,
  },
  {
    name: "Sae Itoshi",
    cumulative_stats: 98,
    stats: {
      speed: 87,
      defense: 73,
      passing: 98,
      dribble: 90,
      shoot: 79,
      offense: 85,
    },
    skills: [
      "Perfect Passing",
      "Advanced Dribbling",
      "Meta-Vision",
      "Off the Ball",
    ],
    position: "Midfielder",
  },
  {
    name: "Aiku Olivier",
    cumulative_stats: 85,
    stats: {
      speed: 85,
      defense: 94,
      passing: 81,
      dribble: 79,
      shoot: 74,
      offense: 72,
    },
    skills: ["Meta-Vision", "Total defense"],
    position: "Defender",
  },
  {
    name: "Baro Shoei",
    cumulative_stats: {},
    stats: {
      speed: 88,
      defense: 75,
      passing: 65,
      dribble: 89,
      shoot: 95,
      offense: 93,
    },
    skills: ["Advanced Shooting", "Chop Dribble", "Predator Eye"],
    position: "Striker",
  },
  {
    name: "Zantetsu Tsurugi",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Niko Ikki",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Chigiri Hyoma",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: ["Speed"],
    position: null,
  },
  {
    name: "Yoichi Isagi",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Meguru Bachira",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Alexis Ness",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Michael Kaiser",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Nijiro Nanase",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Yo Hiori",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Jingo Raichi",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Rensuke Kunigami",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Gin Gagamaru",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Jin Kiyora",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Charles Chevalier",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Tabito Karasu",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Nagi Seishiro",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Mikage Reo",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Eita Otoya",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Genyu Yukimiya",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
  {
    name: "Ryusei Shido",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
    position: null,
  },
];
