[
  {
    name: "Rin Itoshi",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [
      "Perfect Kick Accuracy",
      "Spatial Awareness",
      "Off the Ball",
      "Puppet Soccer",
      "Egotistic Destroyer",
    ],
  },
  {
    name: "Sae Itoshi",
    cumulative_stats: 98,
    stats: {
      speed: 87,
      defense: 73,
      passing: 98,
      dribble: 90,
      shoot: 79,
      offense: 85,
    },
    skills: [
      "Perfect Kick Technique",
      "Counter-Dribbling",
      "Reflex",
      "Meta-Vision",
    ],
  },
  {
    name: "Aiku Oliver",
    cumulative_stats: 85,
    stats: {
      speed: 81,
      defense: 93,
      passing: 83,
      dribble: 76,
      shoot: 77,
      offense: 72,
    },
    skills: [
      "Dominant Physicality",
      "Spatial Awareness",
      "Reflex",
      "Meta-Vision",
    ],
  },
  {
    name: "Baro Shoei",
    cumulative_stats: 92,
    stats: {
      speed: 80,
      defense: 68,
      passing: 61,
      dribble: 88,
      shoot: 96,
      offense: 95,
    },
    skills: ["Charging Skill", "Chop Dribbling", "Middle Shot", "Predator Eye"],
  },
  {
    name: "Zantetsu Tsurugi",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Niko Ikki",
    cumulative_stats: 82,
    stats: {
      speed: 78,
      defense: 84,
      passing: 88,
      dribble: 76,
      shoot: 67,
      offense: 82,
    },
    skills: ["Spatial Awareness", "Watchtower Soccer", "Meta-Vision"],
  },
  {
    name: "Chigiri Hyoma",
    cumulative_stats: 90,
    stats: {
      speed: 98,
      defense: 68,
      passing: 80,
      dribble: 93,
      shoot: 88,
      offense: 95,
    },
    skills: ["Speed", "Golden Zone"],
  },
  {
    name: "Yoichi Isagi",
    cumulative_stats: 88,
    stats: {
      speed: 77,
      defense: 75,
      passing: 78,
      dribble: 70,
      shoot: 82,
      offense: 94,
    },
    skills: ["Meta-Vision (Stage 2)", "Advanced Shooting", "Positioning", ""],
  },
  {
    name: "Meguru Bachira",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Alexis Ness",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Michael Kaiser",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Nijiro Nanase",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Yo Hiori",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Jingo Raichi",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Rensuke Kunigami",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Gin Gagamaru",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Jin Kiyora",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Charles Chevalier",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Tabito Karasu",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Nagi Seishiro",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Mikage Reo",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Eita Otoya",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Genyu Yukimiya",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Ryusei Shido",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Jyubei Aryu",
    cumulative_stats: {},
    stats: {
      speed: null,
      defense: null,
      passing: null,
      dribble: null,
      shoot: null,
      offense: null,
    },
    skills: [],
  },
  {
    name: "Shuto Sendou",
    cumulative_stats: 81,
    stats: {
      speed: 82,
      defense: 73,
      passing: 73,
      dribble: 77,
      shoot: 83,
      offense: 84,
    },
    skills: ["Advanced Shooting"],
  },
];
