[
  {
    name: "Rin Itoshi",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Sae Itoshi",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Aiku Olivier",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Jinpachi Ego",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Baro Shoei",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Zantetsu Tetsuo",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Tsurugi",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Niko Ikki",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Chigiri Hyoma",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Yoichi Isagi",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Meguru Bachira",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Alexis Ness",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Michael Kaiser",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Nijiro Nanase",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Yo Hiori",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Jingo Raichi",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Rensuke Kunigami",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Gin Gagamaru",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Jin Kiyora",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Charles Chevalier",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Tabito Karasu",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Nagi Seishiro",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Mikage Reo",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Eita Otoya",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Genyu Yukimiya",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
  {
    name: "Ryusei Shido",
    cumulative_stats: {},
    stats: {
      speed: null,
      defence: null,
      passing: null,
      dribble: null,
      shoot: null,
      offence: null,
    },
    skills: {},
    position: null,
  },
];
