skills = {
  "1 point": ["Reflex", "Direct Shot", "Manmarking"],
  "3 points": [
    "Spatial Awareness",
    "Off the Ball",
    "Dominant Physicality",
    "Middle Shot",
    "44 Red Panther Sniper",
    "Key Passing",
    "Immense Stamina",
  ],
  "5 points": [
    "Perfect Kick Accuracy",
    "Puppet Soccer",
    "Perfect Kick Technique",
    "Meta-Vision",
    "Charging Skill",
    "Predator Eye",
    "Watchtower Soccer",
    "Flexibility",
    "Counter-Dribbling",
    "Nimble Dribbling",
    "Chop Dribbling",
    "Elastic Dribbling",
    "Gyro Shot",
    "Drive Shot",
    "Jumping Power",
    "Long Reach",
    "Immense Speed",
    "Positioning",
    "Expert Ball Control",
    "Feints",
  ],
  "10 points": [
    "Egotistic Destroyer",
    "Immeasurable Speed",
    "Egocentrism",
    "Two Gun Volley",
    "Monstrance",
    "Kaiser Impact",
    "Ambidexterity",
    "Perfect Ball Control",
    "Trapping",
    "Dexterity",
    "Chameleon Style",
    "Zombie Dribbling",
  ],
};
